 # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  

  # Forward Position Controllers ---------------------------------------
  PositionJointInterface_J0_controller:
    type: position_controllers/JointPositionController
    joint: j0

  PositionJointInterface_J1_controller:
    type: position_controllers/JointPositionController
    joint: j1
    
  PositionJointInterface_J2_controller:
    type: position_controllers/JointPositionController
    joint: j2
    
  PositionJointInterface_J3_controller:
    type: position_controllers/JointPositionController
    joint: j3